version: '3.5'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: tsed-docker-mysql-instance/server:latest
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql://root:password@mysql:3306/tsed_db

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=tsed_db
      - MYSQL_USER=tsed_user
      - MYSQL_PASSWORD=tsed_password
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:

